language: go

go:
	- 1.12.x
	- 1.13.x
	- tip

script:
	- go test ./...
	- go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
	- bash <(curl -s https://codecov.io/bash)

env:
	- GO111MODULE=on
